GET localhost:3000/dishes

###
PUT localhost:3000/dishes
Content-Type: application/json

{
  "id": 1,
  "name": "Test"
}


###
POST localhost:3000/dishes
Content-Type: application/json

{
  "id": 2,
  "name": "Test"
}